/*
 * Generated by ISE 17.01.9.9700 GPL Edition - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F301_6304();
extern void F304_6478();
extern void F305_6482();
extern void F307_6644();
extern void F390_4296();
extern void F341_6184();
extern void F71_1122();
extern EIF_REFERENCE F71_1109();
extern EIF_BOOLEAN F71_1121();
extern EIF_BOOLEAN F71_1126();
extern void F71_1131();
extern void F71_1132();
extern void F71_1133();
extern void F106_1563();
extern EIF_TYPED_VALUE F106_1564();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F301_6304;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F305_6482;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F390_4296;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F304_6478;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F307_6644;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F341_6184;
	egc_is_scoop_capable = 1;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F71_1122;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F71_1121;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F71_1109;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F71_1126;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F71_1131;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F71_1132;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F71_1133;

	egc_str_dtype = 303;

	egc_str32_dtype = 306;
	egc_arr_dtype = 389;
	egc_tup_dtype = 255;
	egc_disp_rout_id = 2020;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x02D9;
	egc_sp_wchar = 0x01F8;
	egc_sp_bool = 0x0264;
	egc_sp_uint8 = 0x021C;
	egc_sp_uint16 = 0x02EB;
	egc_sp_uint32 = 0x0346;
	egc_sp_uint64 = 0x01C4;
	egc_sp_int8 = 0xFFFF;
	egc_sp_int16 = 0xFFFF;
	egc_sp_int32 = 0x016A;
	egc_sp_int64 = 0xFFFF;
	egc_sp_real32 = 0x036A;
	egc_sp_real64 = 0x038E;
	egc_sp_pointer = 0x0323;
	egc_sp_ref = 0x0183;

	egc_uint8_dtype = 278;
	egc_uint16_dtype = 275;
	egc_uint32_dtype = 272;
	egc_uint64_dtype = 269;
	egc_int8_dtype = 266;
	egc_int16_dtype = 263;
	egc_int32_dtype = 260;
	egc_int64_dtype = 257;
	egc_bool_dtype = 293;
	egc_real32_dtype = 281;
	egc_char_dtype = 290;
	egc_wchar_dtype = 287;
	egc_real64_dtype = 284;
	egc_point_dtype = 296;

	egc_exception_dtype = 118;
	egc_except_emnger_dtype = 70;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "ewf_app";
	egc_system_location = "D:\\Innopolis\\EIFFEL PROJECT\\form\\EIFGENs\\ewf_app\\W_code";
	egc_compiler_tag = 38;
	egc_project_version = 1491223324;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 944;

	egc_rcount = 1;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "EWF_APP.make_and_launch";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 1043;
	egc_rcarg[0] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 105;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F106_1563;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F106_1564;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 93; /* EWF_APP */
	}
}

#ifdef __cplusplus
}
#endif
